spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/budget?ssl=false&authMechanism=SCRAM-SHA-1&authSource=admin
      auto-index-creation: true
  session:
    store-type: mongodb